### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by testwill** [anakryiko/bpf-ringbuf-examples#1]
BPF      .output/ringbuf-output.bpf.o
ringbuf-output.bpf.c:11:15: error: use of undeclared identifier 'BPF_MAP_TYPE_RINGBUF'; did you mean 'BPF_MAP_TYPE_UNSPEC'?
        __uint(type, BPF_MAP_TYPE_RINGBUF);
                     ^~~~~~~~~~~~~~~~~~~~
                     BPF_MAP_TYPE_UNSPEC
.output/bpf/bpf_helpers.h:13:39: note: expanded from macro '__uint'
#define __uint(name, val) int (*name)[val]
                                      ^
/usr/include/linux/bpf.h:100:2: note: 'BPF_MAP_TYPE_UNSPEC' declared here
        BPF_MAP_TYPE_UNSPEC,
        ^
1 error generated.
Makefile:57: recipe for target '.output/ringbuf-output.

**Comment by anakryiko** [comment]
You need newer UAPI headers. Either update your kernel and/or kernel-headers package, or use UAPI headers that libbpf ships for its own compilation (https://github.com/libbpf/libbpf/tree/master/include/uapi/linux)

**Comment by testwill** [comment]
ok,thanks
